work_dir: ./work_dir/cub/resent50_cam

num_epoch: 200
# feeder
feeder: feeders.cub.Feeder
num_classes : 200
num_worker : 8
train_feeder_args:
  data_path: data/CUB_200_2011
  phase: train
  size: 448
  aug: True
  aug_N: 2
  aug_M: 5

test_feeder_args:
  data_path: data/CUB_200_2011
  phase: test
  size: 448
  aug: False

# model
model: model.ResNet50_cam.ResNet50_cam
model_args:
  num_classes: 200

#optim
weight_decay: 0.0001
base_lr: 0.001

# training
device: [0,1]
batch_size: 64
test_batch_size: 64

# scheduler
scheduler: StepLR

# random seed
seed: 2023