work_dir: ./work_dir/cub/resent50_cam

# feeder
feeder: feeders.cub.Feeder
num_classes : 100
num_worker : 8
train_feeder_args:
  data_path: data/CUB_200_2011
  phase: train

test_feeder_args:
  data_path: data/CUB_200_2011
  phase: test

# model
model: model.ResNet50_cam.ResNet50_cam
model_args:
  in_channel: 3
  num_classes: 200

#optim
weight_decay: 0.0004
base_lr: 0.0001

# training
device: [0,1]
batch_size: 128
test_batch_size: 128
num_epoch: 30

# scheduler
scheduler: StepLR