work_dir: ./work_dir/cifar100/resent50

# feeder
feeder: cifar100
num_classes : 100
num_worker : 8
train_feeder_args:
  data_path: data/oad/oad.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 32
  normalization: False
  random_rot: False
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/oad/oad.npz
  split: test
  window_size: 32
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ResNet50.ResNet50
model_args:
  in_channel: 3
  num_classes: 100

#optim
weight_decay: 0.0004
base_lr: 0.0001

# training
device: [0,1]
batch_size: 128
test_batch_size: 128
num_epoch: 30

# scheduler
scheduler: StepLR